require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe DatasiftSubscriptionsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # DatasiftSubscription. As you add validations to DatasiftSubscription, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DatasiftSubscriptionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all datasift_subscriptions as @datasift_subscriptions" do
      datasift_subscription = DatasiftSubscription.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:datasift_subscriptions)).to eq([datasift_subscription])
    end
  end

  describe "GET show" do
    it "assigns the requested datasift_subscription as @datasift_subscription" do
      datasift_subscription = DatasiftSubscription.create! valid_attributes
      get :show, {:id => datasift_subscription.to_param}, valid_session
      expect(assigns(:datasift_subscription)).to eq(datasift_subscription)
    end
  end

  describe "GET new" do
    it "assigns a new datasift_subscription as @datasift_subscription" do
      get :new, {}, valid_session
      expect(assigns(:datasift_subscription)).to be_a_new(DatasiftSubscription)
    end
  end

  describe "GET edit" do
    it "assigns the requested datasift_subscription as @datasift_subscription" do
      datasift_subscription = DatasiftSubscription.create! valid_attributes
      get :edit, {:id => datasift_subscription.to_param}, valid_session
      expect(assigns(:datasift_subscription)).to eq(datasift_subscription)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DatasiftSubscription" do
        expect {
          post :create, {:datasift_subscription => valid_attributes}, valid_session
        }.to change(DatasiftSubscription, :count).by(1)
      end

      it "assigns a newly created datasift_subscription as @datasift_subscription" do
        post :create, {:datasift_subscription => valid_attributes}, valid_session
        expect(assigns(:datasift_subscription)).to be_a(DatasiftSubscription)
        expect(assigns(:datasift_subscription)).to be_persisted
      end

      it "redirects to the created datasift_subscription" do
        post :create, {:datasift_subscription => valid_attributes}, valid_session
        expect(response).to redirect_to(DatasiftSubscription.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved datasift_subscription as @datasift_subscription" do
        post :create, {:datasift_subscription => invalid_attributes}, valid_session
        expect(assigns(:datasift_subscription)).to be_a_new(DatasiftSubscription)
      end

      it "re-renders the 'new' template" do
        post :create, {:datasift_subscription => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested datasift_subscription" do
        datasift_subscription = DatasiftSubscription.create! valid_attributes
        put :update, {:id => datasift_subscription.to_param, :datasift_subscription => new_attributes}, valid_session
        datasift_subscription.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested datasift_subscription as @datasift_subscription" do
        datasift_subscription = DatasiftSubscription.create! valid_attributes
        put :update, {:id => datasift_subscription.to_param, :datasift_subscription => valid_attributes}, valid_session
        expect(assigns(:datasift_subscription)).to eq(datasift_subscription)
      end

      it "redirects to the datasift_subscription" do
        datasift_subscription = DatasiftSubscription.create! valid_attributes
        put :update, {:id => datasift_subscription.to_param, :datasift_subscription => valid_attributes}, valid_session
        expect(response).to redirect_to(datasift_subscription)
      end
    end

    describe "with invalid params" do
      it "assigns the datasift_subscription as @datasift_subscription" do
        datasift_subscription = DatasiftSubscription.create! valid_attributes
        put :update, {:id => datasift_subscription.to_param, :datasift_subscription => invalid_attributes}, valid_session
        expect(assigns(:datasift_subscription)).to eq(datasift_subscription)
      end

      it "re-renders the 'edit' template" do
        datasift_subscription = DatasiftSubscription.create! valid_attributes
        put :update, {:id => datasift_subscription.to_param, :datasift_subscription => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested datasift_subscription" do
      datasift_subscription = DatasiftSubscription.create! valid_attributes
      expect {
        delete :destroy, {:id => datasift_subscription.to_param}, valid_session
      }.to change(DatasiftSubscription, :count).by(-1)
    end

    it "redirects to the datasift_subscriptions list" do
      datasift_subscription = DatasiftSubscription.create! valid_attributes
      delete :destroy, {:id => datasift_subscription.to_param}, valid_session
      expect(response).to redirect_to(datasift_subscriptions_url)
    end
  end

end
